imports:
    - { resource: 'currency.yml' }
    - { resource: 'notification.yml' }
    - { resource: 'discount.yml'}

parameters:
    subscriptions.service.class: "Newscoop\\PaywallBundle\\Services\\PaywallService"
    newscoop.paywall.listener.notification.class: "Newscoop\\PaywallBundle\\EventListener\\NotificationListener"

services:
    paywall.subscription.service:
        class:      %subscriptions.service.class%
        arguments:  ["@em", "@user"]
    newscoop.paywall.adapter.manager:
      class: Newscoop\PaywallBundle\Services\PaywallManager
      arguments: ["@em", "@paywall.subscription.service", "@dispatcher", "@router", "%paywall_gateways%"]

    newscoop.paywall.adapter:
      class: Newscoop\PaywallBundle\Adapter\PaywallAdapterInterface
      factory_service: newscoop.paywall.adapter.manager
      factory_method: getAdapter

    newscoop_paywall.lifecyclesubscriber:
        class: Newscoop\PaywallBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
            - @dispatcher
            - @newscoop.scheduler
            - @preferences
        tags:
            - { name: kernel.event_subscriber}

    newscoop_paywall.configure_menu_listener:
        class: Newscoop\PaywallBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments:
            - @translator

    newscoop_paywall.form.type.subscriptionconf:
        class: Newscoop\PaywallBundle\Form\Type\SubscriptionConfType
        tags:
            - { name: form.type, alias: subscriptionconf }

    newscoop_paywall.form.type.specification:
        class: Newscoop\PaywallBundle\Form\Type\SpecificationType
        tags:
            - { name: form.type, alias: specificationForm }

    newscoop_paywall.form.type.subscriptionedit:
        class: Newscoop\PaywallBundle\Form\Type\SubscriptionEditType
        tags:
            - { name: form.type, alias: subscriptioneditForm }

    newscoop_paywall.validator.unique.containsdecimal:
        class: Newscoop\PaywallBundle\Validator\Constraints\ContainsDecimalValidator
        tags:
            - { name: validator.constraint_validator, alias: decimal_validator }

    newscoop_paywall.adapters.listener:
        class: Newscoop\PaywallBundle\EventListener\AdaptersListener
        arguments: ["@em"]
        tags:
          - { name: kernel.event_listener, event: newscoop_paywall.adapters.register, method: registerExternalAdapters }

    newscoop.template_lists.list_objects.listener:
        class: Newscoop\PaywallBundle\EventListener\ListObjectsListener
        tags:
          - { name: kernel.event_listener, event: newscoop.listobjects.register, method: registerObjects }

    newscoop_paywall.criteria.subscriptions_criteria:
        class: Newscoop\PaywallBundle\Criteria\SubscriptionCriteria

    newscoop.template_lists.pricelist:
        class:      Newscoop\PaywallBundle\TemplateList\PriceList
        arguments:  ["@newscoop_paywall.criteria.subscriptions_criteria"]
        tags:
            -  { name: newscoop.template_lists }

    newscoop_paywall.services.order:
        class: Newscoop\PaywallBundle\Services\OrderService
        arguments:
            - @newscoop_paywall.currency_context
            - @newscoop_paywall.currency_converter
            - @paywall.subscription.service
            - @newscoop_paywall.processor.discounts

    newscoop_paywall.services.payment:
        class: Newscoop\PaywallBundle\Services\PaymentService
        arguments:
            - @em
