parameters:
    newscoop.paywall.adapter.class: "Newscoop\\PaywallBundle\\Adapter\\PaypalAdapter"
    subscriptions.service.class: "Newscoop\\PaywallBundle\\Services\\PaywallService"
    newscoop.paywall.listener.notification.class: "Newscoop\\PaywallBundle\\EventListener\\NotificationListener"

services:
    paywall.subscription.service:
        class:      %subscriptions.service.class%
        arguments:  ["@em"]
    newscoop.paywall.adapter.manager:
      class: Newscoop\PaywallBundle\Services\PaywallManager
      arguments: ["@em", "@paywall.subscription.service", "@dispatcher"]

    newscoop.paywall.adapter:
      class: Newscoop\PaywallBundle\Adapter\PaywallAdapterInterface
      factory_service: newscoop.paywall.adapter.manager
      factory_method: getAdapter

    newscoop_paywall.lifecyclesubscriber:
        class: Newscoop\PaywallBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
            - @dispatcher
            - @newscoop.scheduler
            - @preferences
        tags:
            - { name: kernel.event_subscriber}

    newscoop_paywall.configure_menu_listener:
        class: Newscoop\PaywallBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments: 
            - @translator

    newscoop_paywall.form.type.subscriptionconf:
        class: Newscoop\PaywallBundle\Form\Type\SubscriptionConfType
        tags:
            - { name: form.type, alias: subscriptionconf }

    newscoop_paywall.form.type.specification:
        class: Newscoop\PaywallBundle\Form\Type\SpecificationType
        tags:
            - { name: form.type, alias: specificationForm }

    newscoop_paywall.form.type.subscriptionedit:
        class: Newscoop\PaywallBundle\Form\Type\SubscriptionEditType
        tags:
            - { name: form.type, alias: subscriptioneditForm }

    newscoop_paywall.form.type.subscriptionadd:
        class: Newscoop\PaywallBundle\Form\Type\SubscriptionAddType
        tags:
            - { name: form.type, alias: subscriptionaddForm }

    newscoop_paywall.validator.unique.containsdecimal:
        class: Newscoop\PaywallBundle\Validator\Constraints\ContainsDecimalValidator
        tags:
            - { name: validator.constraint_validator, alias: decimal_validator }

    newscoop_paywall.adapters.listener:
        class: Newscoop\PaywallBundle\EventListener\AdaptersListener
        arguments: ["@em"]
        tags:
          - { name: kernel.event_listener, event: newscoop_paywall.adapters.register, method: registerExternalAdapters }

    newscoop.template_lists.list_objects.listener:
        class: Newscoop\PaywallBundle\EventListener\ListObjectsListener
        tags:
          - { name: kernel.event_listener, event: newscoop.listobjects.register, method: registerObjects }

    newscoop_paywall.criteria.subscriptions_criteria:
        class: Newscoop\PaywallBundle\Criteria\SubscriptionCriteria

    newscoop.template_lists.pricelist:
        class:      Newscoop\PaywallBundle\TemplateList\PriceList
        arguments:  ["@newscoop_paywall.criteria.subscriptions_criteria"]
        tags:
            -  { name: newscoop.template_lists }
    newscoop_paywall.notifications_service:
        class: Newscoop\PaywallBundle\Services\NotificationsService
        arguments:
            - @email
            - @preferences
            - @newscoop.templates.service
            - @newscoop.placeholders.service
            - @em
            - @event_dispatcher

    newscoop_paywall.notification_listener:
        class: %newscoop.paywall.listener.notification.class%
        arguments:
            - @newscoop_paywall.notifications_service
        tags:
            - { name: kernel.event_listener, event: paywall.subscription.order, method: sendSubscriptionNotificationEmail }
            - { name: kernel.event_listener, event: paywall.subscription.order, method: sendUserNotificationEmail }
            - { name: kernel.event_listener, event: paywall.subscription.status_change, method: sendUserSubscriptionStatusChangeEmail }
            - { name: kernel.event_listener, event: paywall.subscription.expiration, method: sendSubscriptionExpirationEmail }
            - { name: kernel.event_listener, event: paywall.subscription.admin_order, method: sendAdminCreatedNotification }
