parameters:
    newscoop.paywall.adapter.class: "Newscoop\\PaywallBundle\\Adapter\\PaypalAdapter"
    subscriptions.service.class: "Newscoop\\PaywallBundle\\Services\\PaywallService"

services:
    newscoop.paywall.adapter.manager:
      class: Newscoop\PaywallBundle\Services\PaywallManager
      arguments: ["@em", "@subscription.service"]

    newscoop.paywall.adapter:
      class: Newscoop\PaywallBundle\Adapter\PaywallAdapterInterface
      factory_service: newscoop.paywall.adapter.manager
      factory_method: getAdapter

    newscoop_paywall.lifecyclesubscriber:
        class: Newscoop\PaywallBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}

    newscoop_paywall.configure_menu_listener:
        class: Newscoop\PaywallBundle\EventListener\ConfigureMenuListener
        tags:
          - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }

    newscoop_paywall.form.type.subscriptionconf:
        class: Newscoop\PaywallBundle\Form\Type\SubscriptionConfType
        tags:
            - { name: form.type, alias: subscriptionconf }

    newscoop_paywall.form.type.specification:
        class: Newscoop\PaywallBundle\Form\Type\SpecificationType
        tags:
            - { name: form.type, alias: specificationForm }

    newscoop_paywall.form.type.details:
        class: Newscoop\PaywallBundle\Form\Type\SubscriptionDetailsType
        tags:
            - { name: form.type, alias: detailsForm }

    newscoop_paywall.form.type.subscriptionedit:
        class: Newscoop\PaywallBundle\Form\Type\SubscriptionEditType
        tags:
            - { name: form.type, alias: subscriptioneditForm }

    newscoop_paywall.form.type.subscriptionadd:
        class: Newscoop\PaywallBundle\Form\Type\SubscriptionAddType
        tags:
            - { name: form.type, alias: subscriptionaddForm }

    newscoop_paywall.validator.unique.containsdecimal:
        class: Newscoop\PaywallBundle\Validator\Constraints\ContainsDecimalValidator
        tags:
            - { name: validator.constraint_validator, alias: decimal_validator }