Newscoop\PaywallBundle\Entity\Subscriptions:
    properties:
        name:
            - NotBlank: { message: "step1.form.error.name.blank" }
        price:
            - NotBlank: { message: "step1.form.error.price.blank" }
            - Range:
                min: 1
            - Newscoop\PaywallBundle\Validator\Constraints\ContainsDecimal: { message: "step1.form.error.price.decimal" }
        range:
            - NotBlank: { message: "step1.form.error.range.blank" }
        currency:
            - NotBlank: { message: "step1.form.error.currency.blank" }