Newscoop\PaywallBundle\Entity\Subscriptions:
    properties:
        name:
            - NotBlank: { message: "paywall.step1.form.error.name.blank" }
        price:
            - NotBlank: { message: "paywall.step1.form.error.price.blank" }
            - Range:
                min: 1
            - Newscoop\PaywallBundle\Validator\Constraints\ContainsDecimal: { message: "paywall.step1.form.error.price.decimal" }

Newscoop\PaywallBundle\Entity\Currency:
    properties:
        exchangeRate:
            - NotBlank: { message: "paywall.step1.form.error.price.blank" }
            - Newscoop\PaywallBundle\Validator\Constraints\ContainsDecimal: { message: "paywall.step1.form.error.price.decimal" }