Newscoop\PaywallBundle\Entity\Subscriptions:
    properties:
        price:
            - NotBlank: { message: "Price field can not be empty." }
            - Range:
                min: 1
                minMessage: Value must be greater than 1
            - Newscoop\PaywallBundle\Validator\Constraints\ContainsDecimal: { message: "Price field must be greater or equal 1." }
        range:
            - NotBlank: { message: "Range field can not be empty." }
        currency:
            - NotBlank: { message: "Currency field can not be empty." }